[project]
name = "quantum_irops"
version = "0.1.0"
description = "IROPS pipeline"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "polars>=1.37.1",
]

